In [1]:
import numpy as np

In [2]:
# Task 1

def func(x):
    return 0.1 * x**2 - np.sin(x) + 0.1 * np.cos(x * 5) + 1.


coord_x = np.arange(-5.0, 5.0, 0.1)
coord_y = func(coord_x)

sz = len(coord_x)
sz

100

In [4]:
w = np.array([1.11, -0.26, 0.061,0.0226,0.00178])

In [13]:
X = np.c_[np.ones_like(coord_x), coord_x, coord_x**2, coord_x**3, coord_x**4]

In [15]:
X.shape

(100, 5)

In [16]:
X @ w

array([2.2225    , 2.21587718, 2.20895885, 2.20167342, 2.19395357,
       2.18573625, 2.17696269, 2.16757838, 2.15753309, 2.14678086,
       2.13528   , 2.1229931 , 2.10988701, 2.09593286, 2.08110605,
       2.06538625, 2.04875741, 2.03120774, 2.01272973, 1.99332014,
       1.97298   , 1.95171462, 1.92953357, 1.9064507 , 1.88248413,
       1.85765625, 1.83199373, 1.8055275 , 1.77829277, 1.75032902,
       1.72168   , 1.69239374, 1.66252253, 1.63212294, 1.60125581,
       1.56998625, 1.53838365, 1.50652166, 1.47447821, 1.4423355 ,
       1.41018   , 1.37810246, 1.34619789, 1.31456558, 1.28330909,
       1.25253625, 1.22235917, 1.19289422, 1.16426205, 1.13658758,
       1.11      , 1.08463278, 1.06062365, 1.03811462, 1.01725197,
       0.99818625, 0.98107229, 0.96606918, 0.95334029, 0.94305326,
       0.93538   , 0.9304967 , 0.92858381, 0.92982606, 0.93441245,
       0.94253625, 0.95439501, 0.97019054, 0.99012893, 1.01442054,
       1.04328   , 1.07692622, 1.11558237, 1.1594759 , 1.20883

In [18]:
loss = (X @ w - coord_y)**2

In [20]:
Q = (1/loss.shape[0]) * loss.sum()

In [21]:
Q

0.17749243683224197

In [ ]:
def func(x):
    return 0.1 * x**2 - np.sin(x) + 0.1 * np.cos(x * 5) + 1.


coord_x = np.arange(-5.0, 5.0, 0.1)
coord_y = func(coord_x)
w = np.array([1.11, -0.26, 0.061,0.0226,0.00178])
X = np.c_[np.ones_like(coord_x), coord_x, coord_x**2, coord_x**3, coord_x**4]
loss = (X @ w - coord_y)**2
Q = (1/loss.shape[0]) * loss.sum()

In [ ]:
# Task 2
def func(x):
    return 0.5 * x**2 - 0.1 * 1/np.exp(-x) + 0.5 * np.cos(2*x) - 2.


# здесь объявляйте дополнительные функции (если необходимо)


coord_x = np.arange(-5.0, 5.0, 0.1) # значения отсчетов по оси абсцисс
coord_y = func(coord_x) # значения функции по оси ординат

sz = len(coord_x) # общее число отсчетов

# здесь продолжайте программу
w = [-1.59,-0.69,0.278,0.497,-0.106]
X = np.c_[np.ones_like(coord_x), coord_x, coord_x**2, np.cos(2*coord_x), np.sin(2*coord_x)]
loss = np.abs(X @ w - coord_y)
Q = (1/loss.shape[0]) * loss.sum()

In [23]:
w = [-1.59,-0.69,0.278,0.497,-0.106]

In [24]:
X = np.c_[np.ones_like(coord_x), coord_x, coord_x**2, np.cos(2*coord_x), np.sin(2*coord_x)]

In [25]:
loss = np.abs(X @ w - coord_y)
Q = (1/loss.shape[0]) * loss.sum()

In [26]:
Q

0.9250026294525024

In [60]:
# Task 3

data_x = [(5.8, 1.2), (5.6, 1.5), (6.5, 1.5), (6.1, 1.3), (6.4, 1.3), (7.7, 2.0), (6.0, 1.8), (5.6, 1.3), (6.0, 1.6), (5.8, 1.9), (5.7, 2.0), (6.3, 1.5), (6.2, 1.8), (7.7, 2.3), (5.8, 1.2), (6.3, 1.8), (6.0, 1.0), (6.2, 1.3), (5.7, 1.3), (6.3, 1.9), (6.7, 2.5), (5.5, 1.2), (4.9, 1.0), (6.1, 1.4), (6.0, 1.6), (7.2, 2.5), (7.3, 1.8), (6.6, 1.4), (5.6, 2.0), (5.5, 1.0), (6.4, 2.2), (5.6, 1.3), (6.6, 1.3), (6.9, 2.1), (6.8, 2.1), (5.7, 1.3), (7.0, 1.4), (6.1, 1.4), (6.1, 1.8), (6.7, 1.7), (6.0, 1.5), (6.5, 1.8), (6.4, 1.5), (6.9, 1.5), (5.6, 1.3), (6.7, 1.4), (5.8, 1.9), (6.3, 1.3), (6.7, 2.1), (6.2, 2.3), (6.3, 2.4), (6.7, 1.8), (6.4, 2.3), (6.2, 1.5), (6.1, 1.4), (7.1, 2.1), (5.7, 1.0), (6.8, 1.4), (6.8, 2.3), (5.1, 1.1), (4.9, 1.7), (5.9, 1.8), (7.4, 1.9), (6.5, 2.0), (6.7, 1.5), (6.5, 2.0), (5.8, 1.0), (6.4, 2.1), (7.6, 2.1), (5.8, 2.4), (7.7, 2.2), (6.3, 1.5), (5.0, 1.0), (6.3, 1.6), (7.7, 2.3), (6.4, 1.9), (6.5, 2.2), (5.7, 1.2), (6.9, 2.3), (5.7, 1.3), (6.1, 1.2), (5.4, 1.5), (5.2, 1.4), (6.7, 2.3), (7.9, 2.0), (5.6, 1.1), (7.2, 1.8), (5.5, 1.3), (7.2, 1.6), (6.3, 2.5), (6.3, 1.8), (6.7, 2.4), (5.0, 1.0), (6.4, 1.8), (6.9, 2.3), (5.5, 1.3), (5.5, 1.1), (5.9, 1.5), (6.0, 1.5), (5.9, 1.8)]
data_y = [-1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1, -1, 1, -1, -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, 1, -1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1, -1, -1, -1, -1, 1, -1, 1, 1, 1, 1, 1, -1, -1, 1, -1, -1, 1, -1, 1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 1, 1, -1, -1, 1, 1, 1, -1, 1, -1, -1, -1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 1, -1, 1, 1, -1, -1, -1, -1, 1]
y = np.array(data_y)
# здесь продолжайте программу
X = np.c_[np.ones(len(data_x)), data_x]
w = ((X.T @ y).reshape(1, -1) @ np.linalg.inv(X.T @ X)).squeeze()

In [61]:
w

array([-3.31307062,  0.00617453,  1.95370269])

In [57]:
w.shape

(1, 3)

In [30]:
print(y.shape)
print(X.shape)

(100,)
(100, 3)


In [ ]:
w = ((X.T @ y).reshape(1, -1) @ np.linalg.inv(X.T @ X))

In [54]:
(X.T @ y).reshape(1, -1) @ np.linalg.inv(X.T @ X)

array([[-3.31307062,  0.00617453,  1.95370269]])

In [43]:
w

array([-3.31307062,  0.00617453,  1.95370269])

In [52]:
w

(array([-1.3531934]),)

In [53]:
(X.T @ y).reshape(1, -1)

array([[ 0. , 32.6, 35. ]])

In [45]:
(X.T @ y)

array([ 0. , 32.6, 35. ])

In [46]:
np.linalg.inv(X.T @ X)

array([[ 0.95468792, -0.16720944,  0.06108449],
       [-0.16720944,  0.03550657, -0.03289542],
       [ 0.06108449, -0.03289542,  0.08645981]])