In [2]:
import numpy as np

In [ ]:
# Task 1
x_test = np.array([(9, 6), (2, 4), (-3, -1), (3, -2), (-3, 6), (7, -3), (6, 2)])
x = np.hstack((np.ones(x_test.shape[0]).reshape(-1, 1), x_test))
w = np.array([-14, 7, 5])
predict = np.sign(x @ w.T)
predict

array([ 1.,  1., -1., -1., -1.,  1.,  1.])

In [ ]:
# Task 2
x_test = np.array([(5, -3), (-3, 8), (3, 6), (0, 0), (5, 3), (-3, -1), (-3, 3)])
ones = np.ones(x_test.shape[0])
x = np.hstack((ones.reshape(-1, 1), x_test))
w = np.array([-33, 9, 13])
predict = np.sign(x @ w.T)
predict

array([-1.,  1.,  1., -1.,  1., -1., -1.])

In [5]:
x_test = np.array([(5, -3), (-3, 8), (3, 6), (0, 0), (5, 3), (-3, -1), (-3, 3)])
ones = np.ones(x_test.shape[0])

In [6]:
x_test.shape

(7, 2)

In [19]:
ones.shape

(7,)

In [20]:
ones.reshape(-1, 1).shape

(7, 1)

In [17]:
x = np.hstack((ones.reshape(-1, 1), x_test))

In [22]:
x.shape

(7, 3)

In [25]:
w = np.array([-33, 9, 13])
predict = np.sign(x @ w.T)

In [26]:
predict

array([-1.,  1.,  1., -1.,  1., -1., -1.])

In [21]:
# Task 3
w = np.array([15/7, -9/7, -1])
x_test = np.array([[-8, -4], [-2, 2], [4, 8], [6, 3]]) # задайте самостоятельно (признаки образов: x0, x1, x2)
y_test = np.array([1, 1, -1, 1]) # задайте самостоятельно (метки класса)
x = np.hstack((np.ones(x_test.shape[0]).reshape(-1, 1), x_test))
print(x.shape)
print(w.shape)

(4, 3)
(3,)


In [25]:
x @ w * y_test

array([16.42857143,  2.71428571, 11.        , -8.57142857])

In [36]:
# Task 4
w = np.array([-16, -4, 9]) # задайте самостоятельно (параметры модели: w0, w1, w2 - ориентация разделяющей линии)
x_test = np.array([[1, -5, 2], [1, -4, 6], [1, 3, 2], [1, 3, -3], [1, 5, 6], [1, 9, 2]]) # задайте самостоятельно (признаки образов: x0, x1, x2)
y_test = np.array([1, 1, 1, -1, -1, -1]) # задайте самостоятельно (метки класса)
margin = x_test @ w * y_test

In [37]:
margin

array([ 22,  54, -10,  55, -18,  34])

In [49]:
# Task 5
x_test = np.array([(1, -5, 2), (1, -4, 6), (1, 3, 2), (1, 3, -3), (1, 5, 5), (1, 5, 2), (1, -1, 3)])
y_test = np.array([1, 1, 1, -1, -1, -1, -1])
w = np.array([-8/3, -2/3, 1])
list = y_test * (x_test @ w)
list
Q = np.sum(list > 0)
print(Q)

5
