In [2]:
import numpy as np

In [ ]:
# Task 1
x_test = np.array([(9, 6), (2, 4), (-3, -1), (3, -2), (-3, 6), (7, -3), (6, 2)])
x = np.hstack((np.ones(x_test.shape[0]).reshape(-1, 1), x_test))
w = np.array([-14, 7, 5])
predict = np.sign(x @ w.T)
predict

array([ 1.,  1., -1., -1., -1.,  1.,  1.])

In [ ]:
# Task 2
x_test = np.array([(5, -3), (-3, 8), (3, 6), (0, 0), (5, 3), (-3, -1), (-3, 3)])
ones = np.ones(x_test.shape[0])
x = np.hstack((ones.reshape(-1, 1), x_test))
w = np.array([-33, 9, 13])
predict = np.sign(x @ w.T)
predict

array([-1.,  1.,  1., -1.,  1., -1., -1.])

In [5]:
x_test = np.array([(5, -3), (-3, 8), (3, 6), (0, 0), (5, 3), (-3, -1), (-3, 3)])
ones = np.ones(x_test.shape[0])

In [6]:
x_test.shape

(7, 2)

In [19]:
ones.shape

(7,)

In [20]:
ones.reshape(-1, 1).shape

(7, 1)

In [17]:
x = np.hstack((ones.reshape(-1, 1), x_test))

In [22]:
x.shape

(7, 3)

In [25]:
w = np.array([-33, 9, 13])
predict = np.sign(x @ w.T)

In [26]:
predict

array([-1.,  1.,  1., -1.,  1., -1., -1.])