In [1]:
import numpy as np

In [ ]:
# Task1
np.random.seed(0)
x = np.arange(-1.0, 1.0, 0.1)

size_train = len(x)
w = [0.5, -0.3]
model_a = lambda m_x, m_w: (m_w[1] * m_x + m_w[0])
loss = lambda ax, y: (ax - y) ** 2

y = model_a(x, w) + np.random.normal(0, 0.1, len(x))

In [3]:
model_a(x, w)

array([0.8 , 0.77, 0.74, 0.71, 0.68, 0.65, 0.62, 0.59, 0.56, 0.53, 0.5 ,
       0.47, 0.44, 0.41, 0.38, 0.35, 0.32, 0.29, 0.26, 0.23])

In [4]:
y

array([0.97640523, 0.81001572, 0.8378738 , 0.93408932, 0.8667558 ,
       0.55227221, 0.71500884, 0.57486428, 0.54967811, 0.57105985,
       0.51440436, 0.61542735, 0.51610377, 0.4221675 , 0.42438632,
       0.38336743, 0.46940791, 0.26948417, 0.29130677, 0.14459043])

In [9]:
y_pred = model_a(x, w)
squared_error = (y_pred - y)**2
Q = squared_error.sum() / len(y)
mse = squared_error.mean()

In [8]:
mse

0.010469526728196498

In [10]:
Q

0.010469526728196498

In [ ]:
#Task2
np.random.seed(0)
x = np.arange(-1.0, 1.0, 0.1)


model_a = lambda xx, ww: (ww[0] + ww[1] * xx)
Y = -5.2 + 0.7 * x + np.random.normal(0, 0.1, len(x))

In [21]:
ones = np.ones_like(x)
ones.shape

(20,)

In [23]:
X = np.stack((ones, x), axis=1)
X.shape

(20, 2)

In [24]:
X

array([[ 1.00000000e+00, -1.00000000e+00],
       [ 1.00000000e+00, -9.00000000e-01],
       [ 1.00000000e+00, -8.00000000e-01],
       [ 1.00000000e+00, -7.00000000e-01],
       [ 1.00000000e+00, -6.00000000e-01],
       [ 1.00000000e+00, -5.00000000e-01],
       [ 1.00000000e+00, -4.00000000e-01],
       [ 1.00000000e+00, -3.00000000e-01],
       [ 1.00000000e+00, -2.00000000e-01],
       [ 1.00000000e+00, -1.00000000e-01],
       [ 1.00000000e+00, -2.22044605e-16],
       [ 1.00000000e+00,  1.00000000e-01],
       [ 1.00000000e+00,  2.00000000e-01],
       [ 1.00000000e+00,  3.00000000e-01],
       [ 1.00000000e+00,  4.00000000e-01],
       [ 1.00000000e+00,  5.00000000e-01],
       [ 1.00000000e+00,  6.00000000e-01],
       [ 1.00000000e+00,  7.00000000e-01],
       [ 1.00000000e+00,  8.00000000e-01],
       [ 1.00000000e+00,  9.00000000e-01]])

In [ ]:
w = np.linalg.inv(X.T @ X) @ X.T @ Y

In [ ]:
w.shape

(2,)

In [31]:
w

array([-5.14605924,  0.64014601])

In [32]:
w[0]

-5.146059240324324

In [33]:
w[1]

0.6401460076222646

In [36]:
# Task3
np.random.seed(0)
x = np.arange(-1.0, 1.0, 0.1)


model_a = lambda xx, ww: (ww[0] + ww[1] * xx + ww[2] * xx ** 2 + ww[3] * xx ** 3)
Y = np.sin(x * 5) + 2 * x + np.random.normal(0, 0.1, len(x))

X = np.array([[1, xx, xx**2, xx**3] for xx in x])


In [39]:
Y.shape

(20,)

In [40]:
w = np.linalg.inv(X.T @ X) @ X.T @ Y

In [41]:
w.shape

(4,)

In [42]:
print(w[0], w[1], w[2], w[3])

0.1213227848350132 4.16006062665549 -0.35256615834175453 -4.1933916513993825
