In [12]:
from torch.utils.data import DataLoader, Dataset, TensorDataset
import torch
import numpy as np

In [5]:
t = torch.arange(8, dtype=torch.float32)
data_loader = DataLoader(t)
for item in data_loader:
    print(item)

tensor([0.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])
tensor([6.])
tensor([7.])


In [7]:
data_loader_batch = DataLoader(t, batch_size=3, drop_last=True)
for i, item in enumerate(data_loader_batch, 1):
    print(f'{i}: {item}')

1: tensor([0., 1., 2.])
2: tensor([3., 4., 5.])


In [17]:
class JoinedData(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __len__(self):
        return len(self.x)
    
    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]
    
t_x = torch.rand(4, 3)
t_y = torch.arange(4)

joined_data = JoinedData(t_x, t_y)
joined_data2 = TensorDataset(t_x, t_y)

print(f'len1: {joined_data.__len__()}')
print(f'len2: {joined_data2.__len__()}')

for item1, item2 in zip(joined_data, joined_data2):
    print(item1, item2)


len1: 4
len2: 4
(tensor([0.0166, 0.7069, 0.9113]), tensor(0)) (tensor([0.0166, 0.7069, 0.9113]), tensor(0))
(tensor([0.1598, 0.0535, 0.7595]), tensor(1)) (tensor([0.1598, 0.0535, 0.7595]), tensor(1))
(tensor([0.3099, 0.7539, 0.6916]), tensor(2)) (tensor([0.3099, 0.7539, 0.6916]), tensor(2))
(tensor([0.8634, 0.0837, 0.9914]), tensor(3)) (tensor([0.8634, 0.0837, 0.9914]), tensor(3))


In [18]:
epoches = 2
data_loader = DataLoader(dataset=joined_data, batch_size=2, shuffle=True)
for epoche in range(epoches):
    print(f'epoche {epoche + 1}')
    for item in data_loader:
        print(f'x: {item[0]}, y: {item[1]}')

epoche 1
x: tensor([[0.8634, 0.0837, 0.9914],
        [0.0166, 0.7069, 0.9113]]), y: tensor([3, 0])
x: tensor([[0.3099, 0.7539, 0.6916],
        [0.1598, 0.0535, 0.7595]]), y: tensor([2, 1])
epoche 2
x: tensor([[0.0166, 0.7069, 0.9113],
        [0.1598, 0.0535, 0.7595]]), y: tensor([0, 1])
x: tensor([[0.8634, 0.0837, 0.9914],
        [0.3099, 0.7539, 0.6916]]), y: tensor([3, 2])
