In [2]:
from torch.utils.data import DataLoader
import torch
import numpy as np

In [5]:
t = torch.arange(8, dtype=torch.float32)
data_loader = DataLoader(t)
for item in data_loader:
    print(item)

tensor([0.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])
tensor([6.])
tensor([7.])


In [7]:
data_loader_batch = DataLoader(t, batch_size=3, drop_last=True)
for i, item in enumerate(data_loader_batch, 1):
    print(f'{i}: {item}')

1: tensor([0., 1., 2.])
2: tensor([3., 4., 5.])
