In [1]:
import numpy as np

In [18]:
arr = np.array([1, 2, 3])
print(arr)
print(type(arr))
arr.size

[1 2 3]
<class 'numpy.ndarray'>


3

In [19]:
arr2dim = np.array([[0.5, 2, 3.5], [5, 6, 0.89]])
print(type(arr))
arr2dim.size

<class 'numpy.ndarray'>


6

In [16]:
arr3dim = np.array([[(1, 2), (4.5, 3), (8.6, 7)]], dtype = float)
print(type(arr3dim))
print(arr3dim)

<class 'numpy.ndarray'>
[[[1.  2. ]
  [4.5 3. ]
  [8.6 7. ]]]


In [26]:
ones3x4 = np.ones((3, 4), dtype = float)
ones3x4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
zeros3x2x4 = np.zeros((3, 2, 4))
zeros3x2x4

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [39]:
full7 = np.full((3, 2), 7)
print(full7)

[[7 7]
 [7 7]
 [7 7]]


In [44]:
eye3x5 = np.eye(5)
print(eye3x5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [111]:
a = np.random.random((3, 5))
b = np.random.random((3, 5))
print(a)
print(b)

[[0.64554257 0.41798499 0.23574423 0.80795488 0.68332866]
 [0.57729469 0.96205815 0.3498693  0.56402187 0.13322882]
 [0.91379783 0.08715597 0.80361895 0.99480647 0.63957414]]
[[0.60872457 0.02411425 0.35723583 0.53826651 0.44271071]
 [0.40400632 0.5291988  0.33734393 0.3392368  0.20652291]
 [0.71960494 0.85602708 0.673737   0.5401477  0.15364456]]


In [53]:
arr_ranint = np.random.randint([1, 5, 7, 4], 10)
arr_ranint

array([6, 8, 9, 7])

In [89]:
arange_arr = np.arange(2, 10, 2)
arange_arr.ndim

1

In [68]:
lin_arr = np.linspace(1, 10, 20, endpoint = False, dtype = float)
lin_arr

array([1.  , 1.45, 1.9 , 2.35, 2.8 , 3.25, 3.7 , 4.15, 4.6 , 5.05, 5.5 ,
       5.95, 6.4 , 6.85, 7.3 , 7.75, 8.2 , 8.65, 9.1 , 9.55])

In [91]:
emp3x4 = np.empty((4, 5))
len(emp3x4)

4

zeros
ones
full
eye
linspace
random.random random.randint
arange
empty
-------------------------
.shape
.size
.ndim
len(array)
.dtype
.dtype.name
astype(int)

In [93]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes 

In [ ]:
a + b
np.add(a, b)
a - b
np.subtract(a, b)
a / b
np.divide(a, b)
a * b 
np.multiply(a, b)
np.sin(a)
np.cos(a)
np.log(b)
np.sqrt(a)
np.exp(b)


array([[0.00910815, 0.43773587, 0.02225115, 0.24153372, 0.62295451],
       [0.01797202, 0.12513762, 0.75512964, 0.34935657, 0.02487514],
       [0.44111636, 0.09719184, 0.17723496, 0.2784754 , 0.70609424]])

In [108]:
c= np.array([[1, 2, 5], [3, 4, 7]])
c = c.T
print(c)
print(c.T)
# np.dot(a, b)

[[1 3]
 [2 4]
 [5 7]]
[[1 2 5]
 [3 4 7]]


In [109]:
a

array([[0.06889408, 0.48045826, 0.40441775, 0.2932183 , 0.83037526],
       [0.11038247, 0.15481872, 0.79868864, 0.75850629, 0.03109825],
       [0.94028519, 0.77954878, 0.98947887, 0.51238918, 0.96124504]])

In [112]:
b

array([[0.60872457, 0.02411425, 0.35723583, 0.53826651, 0.44271071],
       [0.40400632, 0.5291988 , 0.33734393, 0.3392368 , 0.20652291],
       [0.71960494, 0.85602708, 0.673737  , 0.5401477 , 0.15364456]])

In [114]:
np.dot(a, b.T)

array([[1.22466527, 0.97673838, 1.52257641],
       [0.86217452, 1.07922879, 1.79981683],
       [1.66405169, 1.15596059, 1.90921863]])

In [115]:
a @ b.T

array([[1.22466527, 0.97673838, 1.52257641],
       [0.86217452, 1.07922879, 1.79981683],
       [1.66405169, 1.15596059, 1.90921863]])

In [116]:
b.T

array([[0.60872457, 0.40400632, 0.71960494],
       [0.02411425, 0.5291988 , 0.85602708],
       [0.35723583, 0.33734393, 0.673737  ],
       [0.53826651, 0.3392368 , 0.5401477 ],
       [0.44271071, 0.20652291, 0.15364456]])

In [117]:
np.transpose(b)

array([[0.60872457, 0.40400632, 0.71960494],
       [0.02411425, 0.5291988 , 0.85602708],
       [0.35723583, 0.33734393, 0.673737  ],
       [0.53826651, 0.3392368 , 0.5401477 ],
       [0.44271071, 0.20652291, 0.15364456]])

In [118]:
b = np.transpose(b)

In [119]:
b

array([[0.60872457, 0.40400632, 0.71960494],
       [0.02411425, 0.5291988 , 0.85602708],
       [0.35723583, 0.33734393, 0.673737  ],
       [0.53826651, 0.3392368 , 0.5401477 ],
       [0.44271071, 0.20652291, 0.15364456]])

In [120]:
a @ b

array([[1.22466527, 0.97673838, 1.52257641],
       [0.86217452, 1.07922879, 1.79981683],
       [1.66405169, 1.15596059, 1.90921863]])

In [121]:
np.array_equal(a, b)

False

In [125]:
a > 0.5

array([[ True, False, False,  True,  True],
       [ True,  True, False,  True, False],
       [ True, False,  True,  True,  True]])

In [126]:
a.sum()

8.815981516684534

In [127]:
a.min()

0.08715596996410335

In [128]:
a.sum(axis = 0)

array([2.13663509, 1.46719911, 1.38923247, 2.36678323, 1.45613162])

In [129]:
a.sum(axis = 1)

array([2.79055534, 2.58647282, 3.43895335])

In [130]:
a

array([[0.64554257, 0.41798499, 0.23574423, 0.80795488, 0.68332866],
       [0.57729469, 0.96205815, 0.3498693 , 0.56402187, 0.13322882],
       [0.91379783, 0.08715597, 0.80361895, 0.99480647, 0.63957414]])

In [131]:
a.max(axis = 0)

array([0.91379783, 0.96205815, 0.80361895, 0.99480647, 0.68332866])

In [136]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [135]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [138]:
a.cumsum(axis = 0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])

In [139]:
np.pi

3.141592653589793

In [140]:
np.e

2.718281828459045

In [143]:
a.mean()

5.0

In [144]:
np.median(a)

5.0

In [145]:
np.corrcoef(a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [146]:
np.mean(a)

5.0

In [147]:
a.mean()

5.0

a.sum()
a.sum(axis = 0)
a.cumsum()
a.mean()
np.median()
a.std()
np.corrcoef(a)
a.min()
a.max()

In [166]:
a = np.random.randint(1, 100, size = (3, 4))
a

array([[85, 26, 86, 39],
       [81, 63, 87, 30],
       [54, 86, 39, 48]])

In [167]:
a.sort()
a

array([[26, 39, 85, 86],
       [30, 63, 81, 87],
       [39, 48, 54, 86]])

In [164]:
a.sort(axis = 0)
a

array([[ 2, 30, 60,  3],
       [42, 41, 80, 40],
       [95, 62, 81, 95]])

In [165]:
a.sort(axis = 1)
a

array([[ 2,  3, 30, 60],
       [40, 41, 42, 80],
       [62, 81, 95, 95]])

In [168]:
def test_copy_knowledge():
    """Проверьте свое понимание"""
    a = np.array([[1, 2], [3, 4]])
    
    # Что произойдет?
    b = a[:1, :]  # view или копия?
    c = a.copy()  # какая копия?
    d = a[[0, 1], :]  # view или копия?
    
    b[0, 0] = 999
    print(f"a[0,0] после b: {a[0,0]}")  # 999
    
    c[0, 0] = 111
    print(f"a[0,0] после c: {a[0,0]}")  # 999
    
    d[0, 0] = 222
    print(f"a[0,0] после d: {a[0,0]}")  # 999

In [170]:
a

array([[26, 39, 85, 86],
       [30, 63, 81, 87],
       [39, 48, 54, 86]])

In [172]:
a.ravel()

array([26, 39, 85, 86, 30, 63, 81, 87, 39, 48, 54, 86])

In [173]:
a

array([[26, 39, 85, 86],
       [30, 63, 81, 87],
       [39, 48, 54, 86]])

In [175]:
a[1, 3]

87

In [176]:
a[1][3]

87

In [177]:
a[:, 2]

array([85, 81, 54])

In [178]:
a[[0, 2], 2]

array([85, 54])

In [179]:
a[1:2, :]

array([[30, 63, 81, 87]])

In [180]:
a[[1], :]

array([[30, 63, 81, 87]])

In [182]:
a[1:2]

array([[30, 63, 81, 87]])

In [183]:
a

array([[26, 39, 85, 86],
       [30, 63, 81, 87],
       [39, 48, 54, 86]])

In [191]:
b = np.append(a, np.array([[1, 2, 3, 4]]), axis = 0)
b

array([[26, 39, 85, 86],
       [30, 63, 81, 87],
       [39, 48, 54, 86],
       [ 1,  2,  3,  4]])

In [192]:
np.array([1, 2]).shape

(2,)

In [193]:
np.array([[1, 2]]).shape


(1, 2)

#creating
np.zeros((3, 5))
np.ones((2, 5), dtype = int)
np.full((4, 5), 2, dtype = int)
np.empty((3, 5))
np.arange(1, 10, 3)
np.random.random(4, 5)  np.random.randint(1, 10, size = (2, 3))
np.linspace(1, 10, 20, endpoint = False)
np.eye(5)
#dtypes
int64
float32
bool
string
#sizes
a.shape()
a.size()
a.ndim()
a.dtype()
a.dtype.name()
len(a)
#arithmetic operation
np.add(a, b) or a + b
np.subtract(a, b) or a - b
np.multiply(a, b) or a * b
np.devide(a, b) or a / b
np.dot(a, b) or a @ b
np.sin(a)
np.cos(a)
np.log(a) ln
np.exp(a)
np.sqrt(a)
#aggrigation functions
a.min()
a.max()
a.mean()
np.median()
np.std(a)
np.corrcoef(a)
a.cumsum(axis = 0)
#indexing
a[2]
a[0, 2]
#slicing
a[2:5, 3:4]
a[:1]
#fancy indexing
a[[2, 3, 4], 0:2]
#boolean indexing
a[a > 5]
#array manipulations
a = np.transpose(a)
a = a.T
np.append(a, np.array([[5, 6]]), axis = 0)
np.delete()
np.insert()
a.resize((5, 6))
np.vstack((a, b))
a.hstack((a, b))
