In [2]:
import torch
import numpy as np

In [14]:
print(torch.__version__)
print(f'cpu: {torch.cpu.device_count()}')
print(f'cuda: {torch.cuda.device_count()}')
print(torch.cuda.is_available())

2.6.0+cpu
cpu: 1
cuda: 0
False


In [25]:
np.set_printoptions(precision=3)
a = [1, 2, 3]
b = np.array([4.4558, 5, 6], dtype = float)
print(b)
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(f't_a: {t_a}')
print(f't_b: {t_b}')

[4.456 5.    6.   ]
t_a: tensor([1, 2, 3])
t_b: tensor([4.4558, 5.0000, 6.0000], dtype=torch.float64)


In [ ]:
torch.random.manual_seed(42)
t = torch.rand(2, 3)
print(f't: {t}')
print(f'shape of t: {t.shape}')
t_tr = torch.transpose(t, 0, 1)
print(f't_tr: {t_tr}')
print(f'shape os t_tr: {t_tr.shape}')

t: tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
shape of t: torch.Size([2, 3])
t_tr: tensor([[0.8823, 0.9593],
        [0.9150, 0.3904],
        [0.3829, 0.6009]])
shape os t_tr: torch.Size([3, 2])


In [41]:
torch.random.manual_seed(42)
t_dim3 = torch.rand(2, 3, 2)
print(f't_dim3: {t_dim3}')
print(f'shape of t_dim3: {t_dim3.shape}')
t_dim3_tr = torch.transpose(t_dim3, 1, 2)
print(f't_dim3_tr: {t_dim3_tr}')
print(f'shape os t_dim3_tr: {t_dim3_tr.shape}')

t_dim3: tensor([[[0.8823, 0.9150],
         [0.3829, 0.9593],
         [0.3904, 0.6009]],

        [[0.2566, 0.7936],
         [0.9408, 0.1332],
         [0.9346, 0.5936]]])
shape of t_dim3: torch.Size([2, 3, 2])
t_dim3_tr: tensor([[[0.8823, 0.3829, 0.3904],
         [0.9150, 0.9593, 0.6009]],

        [[0.2566, 0.9408, 0.9346],
         [0.7936, 0.1332, 0.5936]]])
shape os t_dim3_tr: torch.Size([2, 2, 3])


In [43]:
t_ones5x7 = torch.ones(5, 7)
print(f'(5, 7) ones tensor: {t_ones5x7}')
t2x3 = torch.rand(2, 3)
print(f't2x3: {t2x3}')
print(f't2x3 like zeros tensor: {torch.zeros_like(t2x3)}')

(5, 7) ones tensor: tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])
t2x3: tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])
t2x3 like zeros tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [44]:
t2x1x3x1 = torch.randint(1, 6, size = (2, 1, 3, 1))
print(f't2x1x3x1: {t2x1x3x1}')
t_squeezed = torch.squeeze(t2x1x3x1, (1, 3))
print(f'squeezed: {t_squeezed}')

t2x1x3x1: tensor([[[[5],
          [4],
          [2]]],


        [[[5],
          [3],
          [5]]]])
squeezed: tensor([[5, 4, 2],
        [5, 3, 5]])


In [45]:
t_zeros = torch.zeros(30)
print(t_zeros.reshape(5, 6))

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [3]:
torch.manual_seed(42)
t1 = 2 * torch.rand(4, 5) - 1
t2 = torch.normal(mean=0, std=1, size = (4, 5))
t_mul = torch.multiply(t1, t2)
t_matmul = torch.matmul(t1, torch.transpose(t2, 0, 1))
print(f't_mul: {t_mul}')
print(f't_matmul: {t_matmul}')
print(f't1_sum: {torch.sum(t1, axis=0)}')
print(f't1_std: {torch.std(t1, dim=1)}')
print(f't1_mean: {torch.mean(t1, axis=0)}')

t_mul: tensor([[-0.5796,  0.8950, -0.1876,  1.5438, -0.0076],
        [ 0.0648, -0.7661, -0.4965,  1.1569, -0.5041],
        [-0.9467, -0.0665, -1.0477,  0.1214,  0.0241],
        [-0.3200,  0.9088, -0.0642,  0.6472, -0.3279]])
t_matmul: tensor([[ 1.6640,  2.8046,  0.0170,  1.8216],
        [ 1.2483, -0.5451, -0.1261, -0.6503],
        [ 0.3789,  0.4580, -1.9154,  1.0619],
        [ 0.2810,  0.6053, -0.7354,  0.8439]])
t1_sum: tensor([ 1.6943,  1.3012,  1.2396,  1.4687, -0.2156])
t1_std: tensor([0.5856, 0.6887, 0.3252, 0.4623])
t1_mean: tensor([ 0.4236,  0.3253,  0.3099,  0.3672, -0.0539])


In [13]:
print(torch.linalg.norm(t1, ord=2, dim=1))
print(np.round(np.sqrt(np.sum(np.square(np.array(t1)), axis = 1)), 4))

tensor([1.4900, 1.3921, 1.2598, 0.9586])
[1.49   1.3921 1.2598 0.9586]


In [69]:
t_ones3 = torch.ones(3)
t_zeros2 = torch.zeros(2)
torch.cat((t_ones3, t_zeros2), axis=0)

tensor([1., 1., 1., 0., 0.])

In [65]:
t2x3 = torch.rand(2)
t_3 = torch.rand(2)
torch.stack([t2x3, t_3], axis=1)

tensor([[0.9231, 0.9549],
        [0.5070, 0.0740]])

In [53]:
t = torch.rand((2, 3), requires_grad = True)
t2 = torch.sum(torch.pow(3, t))
t2.backward()
print(t.grad)
t = torch.randint(1, 100, size = (6,))
splits = torch.chunk(t, 2)
print([item.numpy() for item in splits])
print(splits)


tensor([[3.2704, 1.7492, 2.1326],
        [1.2990, 1.6992, 2.8581]])
[array([55, 23, 45], dtype=int64), array([16,  2, 86], dtype=int64)]
(tensor([55, 23, 45]), tensor([16,  2, 86]))


In [55]:
t = torch.rand(5)
splits = torch.split(t, split_size_or_sections=[2, 3])
print(splits)

(tensor([0.7487, 0.1281]), tensor([0.4384, 0.7399, 0.2686]))


In [74]:
t = torch.tensor([1, 2, 3], dtype = int)
print(f'dtype t: {t.dtype}')
t2 = t.to(torch.float64)
print(f'changed dtype t2: {t2.dtype}')

dtype t: torch.int64
changed dtype t2: torch.float64
